apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-team4
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: team4
  source:
    path: components/jenkins
    repoURL: 'https://github.com/spectrocloud/gitops-jenkins.git'
    targetRevision: HEAD
    helm:
      valueFiles: ['../../teams/team4/values-jenkins.yaml']
  project: default
  syncPolicy:
    automated:
      prune: true
      #selfHeal: false
    syncOptions:
    - CreateNamespace=true
