apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team4
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: teams/team4
    repoURL: 'https://github.com/spectrocloud/gitops-jenkins.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      #selfHeal: false
    # syncOptions:
    # - CreateNamespace=true
