{
 "title": "Jenkins Build Status",
 "description": "Provides build health stats for each repo in an org",
 "tags": [
  "devops",
  "jenkins",
  "dev",
  "in-progress"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": "influxdb" },
   {
    "name": "folder",
    "label": "Folder",
    "query": "SHOW TAG VALUES FROM job WITH KEY = \"owner\""
   },
   {
    "name": "job",
    "label": "Job",
    "query": "SHOW TAG VALUES FROM job WITH KEY = repo WHERE \"owner\" =~ /^($folder)$/"
   },
   {
    "name": "branch",
    "label": "Branch",
    "query": "SHOW TAG VALUES FROM job WITH KEY = branch WHERE \"owner\" =~ /^($folder)$/ and \"repo\" =~ /^($job)$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "Passed",
     "measurement": "job",
     "select": [
      [
       { "params": [ "jobtime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "CompletedSuccess" }
     ]
    },
    {
     "alias": "Failed",
     "measurement": "job",
     "select": [
      [
       { "params": [ "jobtime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "CompletedError" }
     ]
    }
   ]
  },
  {
   "title": "Total Build",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "job",
     "select": [
      [
       { "params": [ "jobtime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Build Duration",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "job",
     "select": [
      [
       { "params": [ "jobtime" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Latest Unit Test Result",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "alias": "Passed",
     "measurement": "tests",
     "select": [
      [
       { "params": [ "passed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / (passed + skipped + failed)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "tests",
     "select": [
      [
       { "params": [ "skipped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / (passed + skipped + failed)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "Failed",
     "measurement": "tests",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / (passed + skipped + failed)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Latest Build",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "job",
     "select": [
      [
       { "params": [ "passed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Duration Trend",
   "type": "btplc-trend-box-panel",
   "description": "This graph shows the percentage change of build duration between the latest run and the first one. The graph will be green if value <= 0; yellow if 0 < value <= 25; and red if value > 25",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 4 },
   "format": "ms",
   "targets": [
    {
     "measurement": "job",
     "select": [
      [
       { "params": [ "jobtime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Latest Coverage Result",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "targets": [
    {
     "alias": "Classes",
     "measurement": "coverage",
     "select": [
      [
       { "params": [ "classes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "Lines",
     "measurement": "coverage",
     "select": [
      [
       { "params": [ "lines" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "Branches",
     "measurement": "coverage",
     "select": [
      [
       { "params": [ "conditionals" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Detail",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "measurement": "job",
     "select": [
      [
       { "params": [ "time" ], "type": "field" }
      ],
      [
       { "params": [ "jobname" ], "type": "field" }
      ],
      [
       { "params": [ "trigger" ], "type": "field" }
      ],
      [
       { "params": [ "jobtime" ], "type": "field" }
      ],
      [
       { "params": [ "joburl" ], "type": "field" }
      ],
      [
       { "params": [ "passed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Build Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "#$tag_buildnumber",
     "groupBy": [
      { "params": [ "buildnumber" ], "type": "tag" }
     ],
     "measurement": "job",
     "select": [
      [
       { "params": [ "jobtime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Stage Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_stagename - #$tag_jobname",
     "groupBy": [
      { "params": [ "stagename" ], "type": "tag" },
      { "params": [ "jobname" ], "type": "tag" }
     ],
     "measurement": "stage",
     "select": [
      [
       { "params": [ "stagetime" ], "type": "field" }
      ],
      [
       { "params": [ "jobname" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  { "title": "Unit Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Unit Test Result",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "measurement": "tests",
     "select": [
      [
       { "params": [ "jobname" ], "type": "field" }
      ],
      [
       { "params": [ "passed" ], "type": "field" },
       { "params": [ " / (passed + skipped + failed)" ], "type": "math" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" },
       {
        "params": [
         " /  (passed + skipped + failed)"
        ],
        "type": "math"
       }
      ],
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [
         "  / (passed + skipped + failed)"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "owner", "operator": "=~", "value": "/^$folder$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  }
 ]
}