{
 "title": "POC Dashboard",
 "description": "Provides build health stats for each repo in an org",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": "influxdb" },
   {
    "name": "org",
    "label": "org",
    "query": "SHOW TAG VALUES FROM job WITH KEY = \"owner\""
   },
   {
    "name": "job",
    "label": "job",
    "query": "SHOW TAG VALUES FROM job WITH KEY = repo WHERE \"owner\" =~ /^($org)$/"
   },
   {
    "name": "branch",
    "label": "branch",
    "query": "SHOW TAG VALUES FROM job WITH key = jobname WHERE \"owner\" =~ /^($org)$/ AND \"repo\" =~ /^($job)$/"
   },
   {
    "name": "project_path",
    "label": "project_path",
    "query": "SHOW TAG VALUES FROM job WITH KEY = \"jobname\" WHERE \"jobname\" =~ /^$org\\/$job\\/$branch.*$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Job Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "jobname" ], "type": "tag" },
      { "params": [ "branch" ], "type": "tag" },
      { "params": [ "owner" ], "type": "tag" },
      { "params": [ "repo" ], "type": "tag" }
     ],
     "measurement": "job",
     "query": "SELECT \"jobtime\", \"passed\", \"blockedtime\" FROM \"job\" WHERE (\"repo\" =~ /^$job$/ AND \"owner\" =~ /^$org$/ AND \"jobname\" =~ /^$project_path$.*$/) AND $timeFilter GROUP BY \"jobname\", \"branch\", \"owner\", \"repo\"",
     "select": [
      [
       { "params": [ "jobtime" ], "type": "field" }
      ],
      [
       { "params": [ "passed" ], "type": "field" }
      ],
      [
       { "params": [ "blockedtime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobname", "operator": "=~", "value": "/^$project_path.*$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$job$/" },
      { "condition": "AND", "key": "owner", "operator": "=~", "value": "/^$org$/" }
     ]
    }
   ]
  },
  {
   "title": "Jenkins Data Table",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "measurement": "jenkins_data",
     "query": "SELECT * from jenkins_data",
     "select": [
      [
       { "params": [ "project_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "project_path" ], "type": "field" }
      ],
      [
       { "params": [ "tests_failed" ], "type": "field" }
      ],
      [
       { "params": [ "tests_skipped" ], "type": "field" }
      ],
      [
       { "params": [ "tests_total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_path", "operator": "=~", "value": "/^$project_path$/" }
     ]
    }
   ]
  },
  {
   "title": "JacoCo Data",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "measurement": "jacoco_data",
     "query": "select * from jacoco_data",
     "select": [
      [
       { "params": [ "project_name" ], "type": "field" }
      ],
      [
       { "params": [ "project_path" ], "type": "field" }
      ],
      [
       { "params": [ "build_number" ], "type": "field" }
      ],
      [
       { "params": [ "jacoco_branch_coverage_rate" ], "type": "field" }
      ],
      [
       {
        "params": [
         "jacoco_instruction_coverage_rate"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "jacoco_complexity_coverage_rate"
        ],
        "type": "field"
       }
      ],
      [
       { "params": [ "jacoco_line_coverage_rate" ], "type": "field" }
      ],
      [
       { "params": [ "jacoco_method_coverage_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_path", "operator": "=~", "value": "/^$project_path$/" }
     ]
    }
   ]
  },
  {
   "title": "SonarQube Data",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "measurement": "sonarqube_data",
     "query": "select * from sonarqube_data",
     "select": [
      [
       { "params": [ "project_name" ], "type": "field" }
      ],
      [
       { "params": [ "project_path" ], "type": "field" }
      ],
      [
       { "params": [ "minor_issues" ], "type": "field" }
      ],
      [
       { "params": [ "major_issues" ], "type": "field" }
      ],
      [
       { "params": [ "critical_issues" ], "type": "field" }
      ],
      [
       { "params": [ "vulnerabilities" ], "type": "field" }
      ],
      [
       { "params": [ "bugs" ], "type": "field" }
      ],
      [
       { "params": [ "display_name" ], "type": "field" }
      ],
      [
       { "params": [ "blocker_issues" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_path", "operator": "=~", "value": "/^$project_path$/" }
     ]
    }
   ]
  },
  {
   "title": "Twistlock Data",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "service_name" ], "type": "tag" }
     ],
     "measurement": "twistlock_data",
     "query": "SELECT \"project_name\", \"service_name\", \"low\", \"medium\", \"high\", \"critical\", \"total\" FROM \"twistlock_data\" WHERE (\"project_path\" =~ /^$project_path$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "project_name" ], "type": "field" }
      ],
      [
       { "params": [ "service_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "low" ], "type": "field" }
      ],
      [
       { "params": [ "medium" ], "type": "field" }
      ],
      [
       { "params": [ "high" ], "type": "field" }
      ],
      [
       { "params": [ "critical" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_path", "operator": "=~", "value": "/^$project_path$/" }
     ]
    }
   ]
  },
  { "title": "Unit Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } }
 ]
}