{
 "title": "XPL Pipeline - Overview",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "diff_interval", "query": "24h, 7d" },
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "jenkins_host",
    "label": "Jenkins",
    "query": "SHOW TAG VALUES FROM \"jenkins_data\" WITH KEY = \"jenkins_host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Lastest builds",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project_path" ], "type": "tag" }
     ],
     "measurement": "jenkins_data",
     "query": "SELECT \"build_number\", \"org_name\", \"service_name\", \"branch_name\", \"build_result_ordinal\", \"build_time\", \"tests_total\" FROM \"jenkins_data\" WHERE $timeFilter AND \"jenkins_host\" =~ /^$jenkins_host$/ AND build_result <> '?' AND branch_name !~ /.*-release-\\d.*/ ORDER BY time DESC",
     "select": [
      [
       { "params": [ "build_result" ], "type": "field" }
      ],
      [
       { "params": [ "build_time" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"deploy_status_devcicd_ordinal\" FROM \"jenkins_custom_data\" WHERE $timeFilter AND \"jenkins_host\" =~ /^$jenkins_host$/ ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total builds",
   "type": "stat",
   "description": "Total builds in the selected time filter.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "jenkins_data",
     "query": "SELECT COUNT(\"build_number\") FROM \"jenkins_data\" WHERE $timeFilter AND \"jenkins_host\" =~ /^$jenkins_host$/",
     "select": [
      [
       { "params": [ "project_path" ], "type": "field" },
       { "params": [ "Path" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average build duration per service (DEV branch only)",
   "type": "table",
   "description": "Only successful builds are used to calculate the average build duration",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "project_path" ], "type": "tag" }
     ],
     "measurement": "jenkins_data",
     "query": "SELECT mean(\"build_time\") AS \"Duration\" FROM \"jenkins_data\" WHERE (\"build_result\" = 'SUCCESS' AND \"project_path\" =~ /.*\\/dev$/ AND \"jenkins_host\" =~ /^$jenkins_host$/) AND $timeFilter GROUP BY \"project_path\"",
     "select": [
      [
       { "params": [ "build_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Duration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "build_result", "operator": "=", "value": "SUCCESS" },
      { "condition": "AND", "key": "project_path", "operator": "=~", "value": "/.*\\/(dev|develop)$/" },
      { "condition": "AND", "key": "jenkins_host", "operator": "=~", "value": "/^$jenkins_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "project_path" ], "type": "tag" }
     ],
     "measurement": "jenkins_data",
     "select": [
      [
       { "params": [ "project_build_health" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Health" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "project_path", "operator": "=~", "value": "/.*\\/(dev|develop)$/" },
      { "condition": "AND", "key": "jenkins_host", "operator": "=~", "value": "/^$jenkins_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Deployment Frequency",
   "type": "table",
   "description": "How often an organization successfully releases to prod",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "service_name" ], "type": "tag" },
      { "params": [ "branch_name" ], "type": "tag" }
     ],
     "measurement": "jenkins_custom_data",
     "select": [
      [
       { "params": [ "deploy_status_devcicd_ordinal" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Successful Deployements" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "jenkins_host", "operator": "=~", "value": "/^$jenkins_host$/" },
      { "condition": "AND", "key": "deploy_status_devcicd", "operator": "=", "value": "SUCCESS" }
     ]
    }
   ]
  },
  {
   "title": "Uniques branches built",
   "type": "stat",
   "description": "Uniques branches built in the selected time filter.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "jenkins_data",
     "query": "SELECT COUNT(DISTINCT \"project_path\") AS \"Path\" FROM \"jenkins_data\" WHERE $timeFilter AND \"jenkins_host\" =~ /^$jenkins_host$/",
     "select": [
      [
       { "params": [ "project_path" ], "type": "field" },
       { "params": [ "Path" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "SonarQube (DEV branch only)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total lines of code",
   "type": "stat",
   "description": "On dev branches only",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_project_path",
     "groupBy": [
      { "params": [ "project_path" ], "type": "tag" }
     ],
     "measurement": "sonarqube_data",
     "query": "SELECT last(\"lines_of_code\") FROM \"sonarqube_data\" WHERE (\"jenkins_host\" =~ /^$jenkins_host$/ AND \"project_path\" =~ /.*\\/(dev|develop)$/) AND time <= now() GROUP BY \"project_path\"",
     "select": [
      [
       { "params": [ "lines_of_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "project_path", "operator": "=~", "value": "/.*\\/dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Current vulnerabilities",
   "type": "stat",
   "description": "On dev branches only",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_project_path",
     "groupBy": [
      { "params": [ "project_path" ], "type": "tag" }
     ],
     "measurement": "sonarqube_data",
     "query": "SELECT last(\"vulnerabilities\") FROM \"sonarqube_data\" WHERE (\"jenkins_host\" =~ /^$jenkins_host$/ AND \"project_path\" =~ /.*\\/(dev|develop)$/) AND time <= now() GROUP BY \"project_path\"",
     "select": [
      [
       { "params": [ "vulnerabilities" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "project_path", "operator": "=~", "value": "/.*\\/dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Current bugs",
   "type": "stat",
   "description": "On dev branches only",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_project_path",
     "groupBy": [
      { "params": [ "project_path" ], "type": "tag" }
     ],
     "measurement": "sonarqube_data",
     "query": "SELECT last(\"bugs\") FROM \"sonarqube_data\" WHERE (\"jenkins_host\" =~ /^$jenkins_host$/ AND \"project_path\" =~ /.*\\/(dev|develop)$/) AND time <= now() GROUP BY \"project_path\"",
     "select": [
      [
       { "params": [ "bugs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "project_path", "operator": "=~", "value": "/.*\\/dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Current code smells",
   "type": "stat",
   "description": "On dev branches only",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_project_path",
     "groupBy": [
      { "params": [ "project_path" ], "type": "tag" }
     ],
     "measurement": "sonarqube_data",
     "query": "SELECT last(\"code_smells\") FROM \"sonarqube_data\" WHERE (\"jenkins_host\" =~ /^$jenkins_host$/ AND \"project_path\" =~ /.*\\/(dev|develop)$/) AND time <= now() GROUP BY \"project_path\"",
     "select": [
      [
       { "params": [ "code_smells" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "project_path", "operator": "=~", "value": "/.*\\/dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Current critical issues",
   "type": "stat",
   "description": "On dev branches only",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_project_path",
     "groupBy": [
      { "params": [ "project_path" ], "type": "tag" }
     ],
     "measurement": "sonarqube_data",
     "query": "SELECT last(\"critical_issues\") FROM \"sonarqube_data\" WHERE (\"jenkins_host\" =~ /^$jenkins_host$/ AND \"project_path\" =~ /.*\\/(dev|develop)$/) AND time <= now() GROUP BY \"project_path\"",
     "select": [
      [
       { "params": [ "critical_issues" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "project_path", "operator": "=~", "value": "/.*\\/dev$/" }
     ]
    }
   ]
  },
  {
   "title": "New issues in the last $diff_interval",
   "type": "table",
   "description": "On dev branches only",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "repeat": "diff_interval",
   "targets": [
    {
     "groupBy": [
      { "params": [ "project_path" ], "type": "tag" }
     ],
     "measurement": "sonarqube_data",
     "query": "SELECT last(\"code_smells\") as \"code_smells_now\", last(\"vulnerabilities\") as \"vulnerabilities_now\", last(\"bugs\") as \"bugs_now\", last(\"critical_issues\") as \"critical_issues_now\" FROM \"sonarqube_data\" WHERE (\"jenkins_host\" =~ /^$jenkins_host$/ AND \"project_path\" =~ /.*\\/(dev|develop)$/) AND time <= now() GROUP BY \"project_path\"",
     "select": [
      [
       { "params": [ "lines_of_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "project_path", "operator": "=~", "value": "/.*\\/dev$/" }
     ]
    },
    {
     "alias": "$tag_project_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"code_smells\") as \"code_smells_previous\", last(\"vulnerabilities\") as \"vulnerabilities_previous\", last(\"bugs\") as \"bugs_previous\", last(\"critical_issues\") as \"critical_issues_previous\" FROM \"sonarqube_data\" WHERE (\"jenkins_host\" =~ /^$jenkins_host$/ AND \"project_path\" =~ /.*\\/(dev|develop)$/) AND time <= now() - $diff_interval GROUP BY \"project_path\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "New issues in the last $diff_interval",
   "type": "table",
   "description": "On dev branches only",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project_path" ], "type": "tag" }
     ],
     "measurement": "sonarqube_data",
     "query": "SELECT last(\"code_smells\") as \"code_smells_now\", last(\"vulnerabilities\") as \"vulnerabilities_now\", last(\"bugs\") as \"bugs_now\", last(\"critical_issues\") as \"critical_issues_now\" FROM \"sonarqube_data\" WHERE (\"jenkins_host\" =~ /^$jenkins_host$/ AND \"project_path\" =~ /.*\\/(dev|develop)$/) AND time <= now() GROUP BY \"project_path\"",
     "select": [
      [
       { "params": [ "lines_of_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "project_path", "operator": "=~", "value": "/.*\\/dev$/" }
     ]
    },
    {
     "alias": "$tag_project_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"code_smells\") as \"code_smells_previous\", last(\"vulnerabilities\") as \"vulnerabilities_previous\", last(\"bugs\") as \"bugs_previous\", last(\"critical_issues\") as \"critical_issues_previous\" FROM \"sonarqube_data\" WHERE (\"jenkins_host\" =~ /^$jenkins_host$/ AND \"project_path\" =~ /.*\\/(dev|develop)$/) AND time <= now() - $diff_interval GROUP BY \"project_path\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lines of code over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_project_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "project_path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sonarqube_data",
     "select": [
      [
       { "params": [ "lines_of_code" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "jenkins_host", "operator": "=~", "value": "/^$jenkins_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Critical issues over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_project_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "project_path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sonarqube_data",
     "select": [
      [
       { "params": [ "critical_issues" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "jenkins_host", "operator": "=~", "value": "/^$jenkins_host$/" }
     ]
    }
   ]
  },
  { "title": "JaCoCo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } }
 ]
}