apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-team3
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: team3
  source:
    path: components/grafana
    repoURL: 'https://github.com/spectrocloud/gitops-jenkins.git'
    targetRevision: HEAD
    helm:
      parameters:
      - name: ingress.hosts[0]
        value: grafana-team3.cluster1.discovery.spectrocloud.com
  project: default
  syncPolicy:
    automated:
      prune: true
      #selfHeal: false
    syncOptions:
    - CreateNamespace=true
